# Generated by Django 3.2.5 on 2021-12-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fitting',
            field=models.TextField(default='Comfort Fit'),
        ),
        migrations.AddField(
            model_name='product',
            name='img1',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
