# Generated by Django 3.2.5 on 2021-12-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211219_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.ImageField(default=None, upload_to='media/products'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.ImageField(default=None, upload_to='media/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sex',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], max_length=5),
        ),
    ]
